# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.0-browsers-legacy      
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # build!
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "66:1c:2d:df:68:b3:d2:ac:14:f6:64:a7:c3:8d:fd:0a" 
      - run:
          name: git_user
          command: git config user.name "marcelogft"
      - run:
          name: git_user_email
          command: git config user.email "marcelo.colomer@gft.com"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy
 
