# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.0-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build!
      - run: npm run build
      - persist_to_workspace:
          root: docs/.vuepress/dist
          paths: *
  deploy:
    docker:
      - image: circleci/node:10.15.0-browsers-legacy
    steps:
      - checkout
      - attach_workspace:
          at: docs/.vuepress/dist
      - add_ssh_keys:
          fingerprints:
            - "66:1c:2d:df:68:b3:d2:ac:14:f6:64:a7:c3:8d:fd:0a"
      - run:
          name: dir
          command: cd docs/.vuepress/dist
      - run:
          name: user
          command: |
             git config --global user.email "marcelo.colomer@gft.com"
             git config --global user.name "marcelogft"
      - run:
          name: init
          command: git init
      - run:
          name: add
          command: git add -A
      - run:
          name: commit
          command: git commit -m 'deploy'
      - run:
          name: push
          command: git push -f  https://github.com/marcelogft/fromsources-web master:gh-pages

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy



